'use client'

import { Navbar } from '@/components/navbar'
import { useT } from '@/lib/i18n'

const copy = {
  en: {
    eyebrow: 'Legal',
    title: 'Terms of Service',
    effective: 'Effective July 3, 2026',
    intro:
      'Socratic.dev is operated by Borderless Coding Labs. These terms explain what you can expect from us and what we expect from you. We kept them short and readable on purpose.',
    sections: [
      {
        h: '1. The service',
        body: [
          'Socratic.dev is an educational platform. An AI tutor guides you through coding and system design challenges using questions instead of answers, and tracks an independence score as you go.',
          'The tutor and the challenges are generated by AI. They can contain mistakes, and nothing here is professional, legal, or career advice. Always use your own judgment.',
        ],
      },
      {
        h: '2. Your account',
        body: [
          'You need a valid email address to create an account, and you are responsible for everything that happens under it. Keep your password to yourself.',
          'You must be at least 13 years old to use Socratic.dev.',
        ],
      },
      {
        h: '3. Acceptable use',
        body: [
          'Use the platform to learn, not to break it. You may not abuse the API or automate requests, farm free hints with multiple accounts, try to extract our prompts or trick the tutor into giving you answers, or submit illegal content.',
          'If something feels like it would ruin the experience for other learners, assume it is not allowed.',
        ],
      },
      {
        h: '4. Hints and credits',
        body: [
          'Hints are a virtual currency inside Socratic.dev. They have no monetary value, cannot be exchanged for money, and cannot be transferred.',
          'Every account gets 35 free hints per week. If we offer credit purchases, those purchases are final and non-refundable, and credits are not money.',
        ],
      },
      {
        h: '5. Your content',
        body: [
          'The code, diagrams, and solutions you create are yours. We claim no ownership over them.',
          'You give us a license to process that content so the service can work — storing it, displaying it back to you, and sending it to our AI provider to generate the tutor’s responses.',
        ],
      },
      {
        h: '6. Availability',
        body: [
          'Socratic.dev is in active development (beta). The service is provided as is, without uptime guarantees, and features may change, break, or be discontinued as we build.',
        ],
      },
      {
        h: '7. Termination',
        body: [
          'We may suspend or close accounts that violate these terms, abuse the platform, or put other users at risk.',
        ],
      },
      {
        h: '8. Changes to these terms',
        body: [
          'We may update these terms as the product evolves. If a change is material, we will let you know before it takes effect.',
        ],
      },
      {
        h: '9. Contact',
        body: [
          'Questions about these terms? Write to luizrenan179@gmail.com.',
        ],
      },
    ],
  },
  pt: {
    eyebrow: 'Legal',
    title: 'Termos de Uso',
    effective: 'Vigente desde 3 de julho de 2026',
    intro:
      'O Socratic.dev é operado pela Borderless Coding Labs. Estes termos explicam o que você pode esperar de nós e o que esperamos de você. Fizemos de propósito um texto curto e legível.',
    sections: [
      {
        h: '1. O serviço',
        body: [
          'O Socratic.dev é uma plataforma educacional. Um tutor de IA guia você por desafios de código e system design usando perguntas em vez de respostas, e acompanha seu score de independência ao longo do caminho.',
          'O tutor e os desafios são gerados por IA. Eles podem conter erros, e nada aqui é aconselhamento profissional, jurídico ou de carreira. Use sempre o seu próprio julgamento.',
        ],
      },
      {
        h: '2. Sua conta',
        body: [
          'Você precisa de um email válido para criar uma conta, e é responsável por tudo o que acontece nela. Mantenha sua senha só com você.',
          'Você precisa ter pelo menos 13 anos para usar o Socratic.dev.',
        ],
      },
      {
        h: '3. Uso aceitável',
        body: [
          'Use a plataforma para aprender, não para quebrá-la. Não é permitido abusar da API ou automatizar requisições, farmar hints grátis com múltiplas contas, tentar extrair nossos prompts ou enganar o tutor para conseguir respostas, nem enviar conteúdo ilegal.',
          'Se algo parece que estragaria a experiência dos outros, assuma que não é permitido.',
        ],
      },
      {
        h: '4. Hints e créditos',
        body: [
          'Hints são uma moeda virtual dentro do Socratic.dev. Eles não têm valor monetário, não podem ser trocados por dinheiro e não podem ser transferidos.',
          'Toda conta recebe 35 hints grátis por semana. Se oferecermos compra de créditos, essas compras são finais e não reembolsáveis, e créditos não são dinheiro.',
        ],
      },
      {
        h: '5. Seu conteúdo',
        body: [
          'O código, os diagramas e as soluções que você cria são seus. Não reivindicamos nenhuma propriedade sobre eles.',
          'Você nos dá uma licença para processar esse conteúdo para que o serviço funcione — armazenar, exibir de volta para você e enviar ao nosso provedor de IA para gerar as respostas do tutor.',
        ],
      },
      {
        h: '6. Disponibilidade',
        body: [
          'O Socratic.dev está em desenvolvimento ativo (beta). O serviço é fornecido como está, sem garantia de uptime, e features podem mudar, quebrar ou ser descontinuadas enquanto construímos.',
        ],
      },
      {
        h: '7. Encerramento',
        body: [
          'Podemos suspender ou encerrar contas que violem estes termos, abusem da plataforma ou coloquem outros usuários em risco.',
        ],
      },
      {
        h: '8. Mudanças nos termos',
        body: [
          'Podemos atualizar estes termos conforme o produto evolui. Se uma mudança for material, avisaremos antes de ela entrar em vigor.',
        ],
      },
      {
        h: '9. Contato',
        body: [
          'Dúvidas sobre estes termos? Escreva para luizrenan179@gmail.com.',
        ],
      },
    ],
  },
}

export default function TermsPage() {
  const t = useT(copy)
  return (
    <div className='bg-background relative flex min-h-screen flex-col'>
      <Navbar />
      <main className='container-main flex-1 pt-[120px] pb-24 md:pb-32'>
        <div className='max-w-2xl'>
          <p className='text-muted-foreground font-mono text-[11px] tracking-[0.14em] uppercase'>
            {t.eyebrow}
          </p>
          <h1 className='font-heading text-ink mt-3 text-[32px] leading-none font-light tracking-[-0.03em] sm:text-[40px]'>
            {t.title}
          </h1>
          <p className='text-muted-foreground mt-4 font-mono text-[11px] tracking-[0.14em] uppercase'>
            {t.effective}
          </p>
          <p className='text-muted-foreground mt-8 text-[15px] leading-relaxed'>
            {t.intro}
          </p>
          <div className='mt-12 flex flex-col gap-10'>
            {t.sections.map((s) => (
              <section key={s.h} className='border-border border-t pt-8'>
                <h2 className='font-heading text-ink text-[22px] leading-tight font-light tracking-[-0.02em]'>
                  {s.h}
                </h2>
                {s.body.map((p) => (
                  <p
                    key={p}
                    className='text-muted-foreground mt-4 text-[15px] leading-relaxed'
                  >
                    {p}
                  </p>
                ))}
              </section>
            ))}
          </div>
        </div>
      </main>
    </div>
  )
}
